import React, { useEffect, useRef, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { generateExpertBrief } from "@/lib/api";
import { useProfile } from "@/lib/useProfile";

const inputClass =
  "bg-[#F3EEE0]/60 border border-[#D9D0B8]/60 rounded-lg px-3 py-2 text-sm text-[#221F17] focus:outline-none focus:border-[#2C5282]/60 transition-colors w-full";

export default function ExpertBriefPage() {
  const { profileId } = useProfile();
  const [searchParams] = useSearchParams();
  const [conversationId, setConversationId] = useState(searchParams.get("conversation_id") || "");
  const [documentId, setDocumentId] = useState(searchParams.get("document_id") || "");
  const [notes, setNotes] = useState(searchParams.get("notes") || "");
  const [markdown, setMarkdown] = useState("");
  const [loading, setLoading] = useState(false);
  const autoGenerated = useRef(false);
  const prefilled = Boolean(searchParams.get("conversation_id") || searchParams.get("document_id"));

  const generate = async () => {
    setLoading(true);
    try {
      const md = await generateExpertBrief({
        profile_id: profileId || null,
        conversation_id: conversationId || null,
        document_id: documentId || null,
        extra_notes: notes || null,
      });
      setMarkdown(md);
    } catch (e) {
      alert("Failed to generate brief. Is the backend running?");
    } finally {
      setLoading(false);
    }
  };

  // If we arrived here via a "Generate Expert Brief" deep link (e.g. from a
  // low-confidence chat answer), auto-generate once so it feels like one click.
  useEffect(() => {
    if (prefilled && !autoGenerated.current) {
      autoGenerated.current = true;
      generate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [prefilled]);

  const download = () => {
    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "expert-review-brief.md";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="mx-auto max-w-3xl px-4 py-8">
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-[#1B1712] flex items-center gap-2">📄 Expert Review Brief</h1>
        <p className="text-sm text-[#4B4636] mt-1">
          One-click structured case brief you can hand to an IP attorney or AYUSH consultant.
        </p>
        {prefilled && (
          <p className="text-xs text-[#17315C] mt-2 bg-[#2C5282]/10 border border-[#2C5282]/30 rounded-lg px-3 py-2 inline-block">
            ✨ Pre-filled from your conversation — generating automatically.
          </p>
        )}
      </div>

      <div className="bg-[#F3EEE0]/40 border border-[#E9E2CD] rounded-xl p-6 flex flex-col gap-3 mb-6">
        <p className="text-xs text-[#6E6754]">
          Profile: {profileId ? <span className="text-[#245C40]">linked ({profileId.slice(0, 8)}…)</span> : "none — create one in Digital Twin"}
        </p>
        <label className="text-sm text-[#4B4636]">
          Conversation ID (optional — copy from a chat session if you want it included)
          <input className={inputClass + " mt-1.5"} value={conversationId} onChange={(e) => setConversationId(e.target.value)} placeholder="conversation_id" />
        </label>
        <label className="text-sm text-[#4B4636]">
          Document ID (optional — from an uploaded PDF)
          <input className={inputClass + " mt-1.5"} value={documentId} onChange={(e) => setDocumentId(e.target.value)} placeholder="document_id" />
        </label>
        <label className="text-sm text-[#4B4636]">
          Additional notes for the attorney/consultant
          <textarea className={inputClass + " mt-1.5"} rows={3} value={notes} onChange={(e) => setNotes(e.target.value)} />
        </label>
        <button onClick={generate} disabled={loading} className="self-start bg-[#17315C] hover:bg-[#2C5282] disabled:opacity-50 text-white text-sm font-medium rounded-lg px-4 py-2.5 transition-colors">
          {loading ? "Generating…" : "Generate Brief"}
        </button>
      </div>

      {loading && (
        <div className="bg-[#F3EEE0]/40 border border-[#E9E2CD] rounded-xl p-6 flex flex-col gap-2.5">
          <div className="h-3 w-1/4 skeleton mb-1" />
          <div className="h-3 w-full skeleton" />
          <div className="h-3 w-full skeleton" />
          <div className="h-3 w-5/6 skeleton" />
          <div className="h-3 w-3/6 skeleton" />
        </div>
      )}

      {!loading && markdown && (
        <div className="bg-[#F3EEE0]/40 border border-[#E9E2CD] rounded-xl p-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-sm font-semibold text-[#2E2B22] uppercase tracking-wide">Preview</h2>
            <button onClick={download} className="text-xs bg-[#255740]/80 hover:bg-[#2F6B4F]/80 text-white rounded-lg px-3 py-1.5">
              Download .md
            </button>
          </div>
          <pre className="text-xs text-[#2E2B22] whitespace-pre-wrap leading-relaxed font-sans">{markdown}</pre>
        </div>
      )}

      {!loading && !markdown && (
        <div className="text-sm text-[#6E6754] border border-dashed border-[#D9D0B8] rounded-xl p-8 text-center">
          Your generated brief will appear here — ready to preview and download as Markdown.
        </div>
      )}
    </div>
  );
}
