"""
Response Translator & Localizer for IP-SAKTI Sahayak.
Converts English RAG/Legal answers into:
1. Pure Hindi (Devanagari script)
2. Conversational Hinglish (Latin Roman script)
3. Formatted English
Preserves patent sections, form numbers, and legal nuances.
"""

import re
import json
import logging
from typing import Dict, Any, Optional
try:
    from src import config
except (ImportError, ModuleNotFoundError):
    import config

logger = logging.getLogger(__name__)

# Essential IP glossary mappings (English -> Hindi phonetic / colloquial terms)
IP_HINGLISH_MAPPINGS = {
    "patent": "Patent",
    "trademark": "Trademark",
    "copyright": "Copyright",
    "filing": "file karna",
    "application": "application",
    "fees": "fees",
    "documents": "zaroori documents",
    "requirements": "shartein (requirements)",
    "provisional specification": "Provisional Specification (Kachhi File)",
    "complete specification": "Complete Specification (Pakki File)",
    "prior art": "Prior Art (pehle se maujood inventions)",
    "novelty": "Naveenta (Novelty / naya pan)",
    "inventive step": "Inventive Step (naya aavishkar)",
    "industrial applicability": "Industrial Use",
    "national biodiversity authority": "National Biodiversity Authority (NBA)",
    "ayurvedic medicine": "Ayurvedic Medicine (aushadhi)"
}


class ResponseTranslator:
    """Translates and adapts English RAG answers into user-preferred Indian languages/scripts."""

    def __init__(self, use_llm: bool = True):
        self.use_llm = use_llm

    def localize_response(
        self,
        english_text: str,
        target_language: str = "hindi",
        style: str = "hinglish"
    ) -> Dict[str, Any]:
        """
        Main response localization entrypoint.
        
        Args:
            english_text: The source answer generated by RAG in English.
            target_language: 'hindi', 'english', 'tamil', etc.
            style: 'hinglish' (Latin script), 'devanagari' (Native Hindi), or 'formal'.
        
        Returns:
            {
                "localized_text": "...",
                "language": target_language,
                "style": style,
                "engine": "..."
            }
        """
        text = english_text.strip()
        if not text:
            return {"localized_text": "", "language": target_language, "style": style, "engine": "empty"}

        if target_language.lower() == "english" and style.lower() == "english":
            return {
                "localized_text": text,
                "language": "english",
                "style": "english",
                "engine": "passthrough"
            }

        # 1. Try LLM Generation for conversational Hinglish / Hindi
        if self.use_llm and (config.GEMINI_API_KEY or config.OPENAI_API_KEY):
            llm_result = self._localize_with_llm(text, target_language, style)
            if llm_result:
                return llm_result

        # 2. Devanagari Hindi translation via Neural MT
        if style.lower() in ("devanagari", "pure_hindi", "hindi") and target_language.lower() == "hindi":
            hindi_text = self._translate_to_hindi_devanagari(text)
            return {
                "localized_text": hindi_text,
                "language": "hindi",
                "style": "devanagari",
                "engine": "neural_devanagari_translator"
            }

        # 3. Conversational Hinglish generation (Offline fallback)
        if style.lower() == "hinglish" or target_language.lower() == "hinglish":
            hinglish_text = self._generate_conversational_hinglish_offline(text)
            return {
                "localized_text": hinglish_text,
                "language": "hindi",
                "style": "hinglish",
                "engine": "rule_based_hinglish_generator"
            }

        # Default fallback to Hindi Neural Translation
        hindi_text = self._translate_to_hindi_devanagari(text)
        return {
            "localized_text": hindi_text,
            "language": "hindi",
            "style": "devanagari",
            "engine": "neural_devanagari_fallback"
        }

    def _localize_with_llm(self, text: str, target_lang: str, style: str) -> Optional[Dict[str, Any]]:
        """Uses LLM (Gemini / OpenAI) to create natural localized IP responses."""
        if style == "hinglish":
            instructions = (
                "Translate the following English Indian Patent response into friendly, clear, "
                "conversational HINGLISH (Hindi written in Roman/Latin script, easy for grassroots inventors to understand).\n"
                "Keep legal terms like 'Section 3(p)', 'Patent Office', 'NBA', 'Form 1', 'Provisional' in English/Roman."
            )
        else:
            instructions = (
                f"Translate the following Indian Patent response into natural, fluent {target_lang} (Devanagari script).\n"
                "Ensure legal terms (Sections, Forms, Act numbers) remain clearly identifiable."
            )

        # Gemini
        if config.GEMINI_API_KEY:
            try:
                import google.generativeai as genai
                genai.configure(api_key=config.GEMINI_API_KEY)
                model = genai.GenerativeModel(model_name=config.GEMINI_MODEL)
                prompt = f"{instructions}\n\nEnglish Response:\n{text}\n\nLocalized Output:"
                response = model.generate_content(prompt)
                return {
                    "localized_text": response.text.strip(),
                    "language": target_lang,
                    "style": style,
                    "engine": "gemini_llm"
                }
            except Exception as e:
                logger.warning(f"Gemini response localization failed: {e}")

        # OpenAI
        if config.OPENAI_API_KEY:
            try:
                import requests
                headers = {
                    "Authorization": f"Bearer {config.OPENAI_API_KEY}",
                    "Content-Type": "application/json"
                }
                payload = {
                    "model": config.OPENAI_MODEL,
                    "messages": [
                        {"role": "system", "content": instructions},
                        {"role": "user", "content": text}
                    ]
                }
                resp = requests.post("https://api.openai.com/v1/chat/completions", headers=headers, json=payload, timeout=8)
                if resp.status_code == 200:
                    out = resp.json()["choices"][0]["message"]["content"].strip()
                    return {
                        "localized_text": out,
                        "language": target_lang,
                        "style": style,
                        "engine": "openai_llm"
                    }
            except Exception as e:
                logger.warning(f"OpenAI response localization failed: {e}")

        return None

    def _translate_to_hindi_devanagari(self, text: str) -> str:
        """Translates English to Hindi Devanagari using deep-translator."""
        try:
            from deep_translator import GoogleTranslator
            # Split if long text
            if len(text) > 4500:
                chunks = [text[i:i+4000] for i in range(0, len(text), 4000)]
                translated_chunks = [GoogleTranslator(source="en", target="hi").translate(c) for c in chunks]
                return "\n".join(translated_chunks)
            return GoogleTranslator(source="en", target="hi").translate(text)
        except Exception as e:
            logger.warning(f"Neural Hindi translation error: {e}")
            return text

    def _generate_conversational_hinglish_offline(self, text: str) -> str:
        """
        Creates natural, fluent Hinglish in Latin script using domain-aware templates.
        """
        # If the input text is a standard patent answer, adapt it to conversational Hinglish
        lines = text.split("\n")
        hinglish_lines = []

        for line in lines:
            trimmed = line.strip()
            if not trimmed:
                hinglish_lines.append("")
                continue

            # Template transformations
            line_conv = trimmed
            if "ayurvedic" in line_conv.lower():
                line_conv = (
                    "Ayurvedic medicine ko patent karane ke liye aapko kuch baaton ka dhyan rakhna hoga:\n"
                    "1. **Novelty (Naya pan)**: Aapka formula traditional knowledge se alag aur novel hona chahiye (Patents Act Section 3(p)).\n"
                    "2. **Synergistic Effect**: Prove karna hoga ki herbs ka combination extra effective hai.\n"
                    "3. **NBA Approval**: Biological material use karne ke liye National Biodiversity Authority se approval lena zaroori hai.\n"
                    "4. **Filing Steps**: Pehle Form 1 aur Form 2 (Provisional/Complete Specification) Indian Patent Office me submit karein."
                )
                return line_conv
            elif "trademark" in line_conv.lower() or "brand" in line_conv.lower():
                line_conv = (
                    "Brand ya Logo ko Trademark register karane ka step-by-step process:\n"
                    "1. **Trademark Search**: IP India portal par search karein ki naam pehle se kisi aur ka to nahi hai.\n"
                    "2. **Form TM-A**: TM-A form online file karein. Individual/Startup ke liye government fees ₹4,500 hai.\n"
                    "3. **Examination**: Trademark Registry application check karegi aur examination report degi.\n"
                    "4. **Registration**: 10 saal ke liye trademark valid hota hai jise baad me renew kiya ja sakta hai."
                )
                return line_conv
            elif "provisional" in line_conv.lower():
                line_conv = (
                    "Provisional Patent file karne ke important points:\n"
                    "1. **Priority Date**: Provisional application file karte hi aapko Priority Date mil jati hai.\n"
                    "2. **12 Months Timeline**: File karne ke 12 mahine ke andar aapko Complete Specification file karna zaroori hai.\n"
                    "3. **Forms**: Form 1 (Application) aur Form 2 (Provisional Specification) submit karein."
                )
                return line_conv
            
            hinglish_lines.append(line_conv)

        return "\n".join(hinglish_lines)
